<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{dc601566-8139-4f5a-b1ac-259dda6c5dad}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
VesselControll_Program :	VesselControlFB ;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[VesselControll_Program();]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>